Models/ErrorViewModel.cs
namespace FirstMVCProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProfileModel.cs
using System.ComponentModel.DataAnnotations;

namespace FirstMVCProject.Models
{
    public class ProfileModel
    {
        [Key]
        public int? ID { get; set; }

        public string? Name { get; set; }

        public string? Surname { get; set; }

        public DateTime DOB { get; set; }

        public int? Age { get; set; }

        public string? Country { get; set; }

        public string? City { get; set; }

    }
}

Models/VeiwModels/ErrorViewModel.cs
namespace FirstMVCProject.Models.VeiwModels
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using FirstMVCProject.Models.VeiwModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FirstMVCProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NduduzoController.cs
using FirstMVCProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FirstMVCProject.Controllers
{
    public class NduduzoController : Controller
    {
        private readonly ILogger<NduduzoController> _logger;

        public NduduzoController(ILogger<NduduzoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using FirstMVCProject.Models;
using FirstMVCProject.Data;
using Microsoft.EntityFrameworkCore;

namespace FirstMVCProject.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ProfileContext _context;

        public ProfileController(ProfileContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.UserProfiles.ToListAsync());
        }

        public IActionResult AddUser()
        {
            var data = HttpContext.Request.Form;

            _context.AddRange(new ProfileModel()
            {
                Name = data["firstname"],
                Surname = data["lastname"],
                DOB = Convert.ToDateTime(data["dob"]),
                Age = int.TryParse(data["age"], out int output) ? output : 0,
                Country = data["country"],
                City = data["city"]
            });

            _context.SaveChanges();

            return new RedirectResult($"/Profile");
        }

        public async Task<IActionResult> EditUser(int? id)
        {
            var userProfile = await _context.UserProfiles.FindAsync(id);

            if (userProfile == null)
                return NotFound();

            return View(userProfile);
        }

        public IActionResult EditSelectedUser()
        {
            var data = HttpContext.Request.Form;

            if (data == null)
                return NotFound();

            var editedProfile = new ProfileModel()
            {
                ID = int.TryParse(data["id"], out int output) ? output : 0,
                Name = data["firstname"],
                Surname = data["lastname"],
                DOB = Convert.ToDateTime(data["dob"]),
                Age = int.TryParse(data["age"], out output) ? output : 0,
                Country = data["country"],
                City = data["city"]
            };

            _context.UserProfiles.Update(editedProfile);
            _context.SaveChanges();

            return new RedirectResult("/Profile");
        }

        public IActionResult DeleteUser(int id)
        {
            var profile = _context.UserProfiles.Find(id);

            if (profile == null)
                return NotFound();

            _context.UserProfiles.Remove(profile);
            _context.SaveChanges();

            return new RedirectResult("/Profile");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Nduduzo/Index.cshtml
<div>
    <h1>Welcome to my custom page</h1>

    <div class="container w-80">
        <div class="row py-5">
        <div class="col-sm">
            <p>This button will take you to the home page</p>

            <a class="btn btn-secondary" asp-controller="Home" asp-action="Index" >
                Take me to home
            </a>
        </div>
        <div class="col-sm">
            <p>This button will take you to the privacy page</p>
            <a class="btn btn-primary" asp-controller="Home" asp-action="Privacy" >
                Take me to privacy
            </a>
        </div>
    </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FirstMVCProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FirstMVCProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FirstMVCProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nduduzo" asp-action="Index">Nduduzo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="Index">Profile</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FirstMVCProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>